# Site
name: SaraLovesDog
description: Technical diary of a data analyst
meta_description: "Data science, Data engineering, DevOps, Machine Learning"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
paginate: 15
url: "https://howtoanalyse.github.io"
baseurl: ""
google_analytics: 'UA-96859607-3'
disqus: 'greendata-1'
mailchimp-list: 

permalink: '/:title/'

# Authors
authors:
  sara:
    name: Sara
    display_name: Sara
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: bitit1994@gmail.com
    web: https://howtoanalyse.github.io
    twitter: 
    description: "Data analyst for mental health"

# Plugins
gems: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/:name/'
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
