# Site
name: Xinyi2016
description: Technical diary of a data analyst
meta_description: "Data science, Data engineering, DevOps, Machine Learning, Sara Zeng, Saralovesdogs, tutorial, How to analyse, HowtoAnalyse"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
paginate: 15
url: "https://Xinyi2016.github.io"
baseurl: ""
google_analytics: 'UA-96859607-3'
disqus: 'greendata-1'
mailchimp-list: 

permalink: '/:title/'
exclude: ["README.md", "pybook"]
# Authors
authors:
  sara:
    name: Sara
    display_name: Sara
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: bitit1994@gmail.com
    web: https://Xinyi2016.github.io
    twitter: 
    description: "Data analyst for mental health"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
